#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds001761-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001761-fmriprep/.reproman/jobs/local/20220225-180901-8eec/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001761-fmriprep/.reproman/jobs/local/20220225-180901-8eec/stderr

#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=48:00:00
#SBATCH --partition=small

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001761-fmriprep/.reproman/jobs/local/20220225-180901-8eec

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 3); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun